export const plansData = [
  {
    id: 1,
    type: 'Bronze',
    price: 'R$ 30',
    collaborators: '5 colaboradores',
    registerArea: true,
    dashboard: true,
    exclusiveSupport: false,
    corporateEmail: false,
  },
  {
    id: 2,
    type: 'Prata',
    price: 'R$ 50',
    collaborators: '10 colaboradores',
    registerArea: true,
    dashboard: true,
    exclusiveSupport: false,
    corporateEmail: false,
  },
  {
    id: 3,
    type: 'Ouro',
    price: 'R$ 100',
    collaborators: '20 colaboradores',
    registerArea: true,
    dashboard: true,
    exclusiveSupport: true,
    corporateEmail: false,
  },
  {
    id: 4,
    type: 'Platina',
    price: 'R$ 200',
    collaborators: 'Acessos ilimitados',
    registerArea: true,
    dashboard: true,
    exclusiveSupport: true,
    corporateEmail: true,
  },
]